### ISSUE TITLE
Plugin Error on Version 1.18.2

### ISSUE THREAD

**Issue by bluestormhunter** [YouHaveTrouble/PurpurExtras#8]
Using release 1.13 the following error appears when trying to start with Purpur 1.18.2:

[00:34:31 ERROR]: Could not load 'plugins/PurpurExtras-1.13.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoSuchMethodError: 'net.kyori.adventure.text.minimessage.MiniMessage$Builder net.kyori.adventure.text.minimessage.MiniMessage$Builder.removeDefaultTransformations()'
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:157) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:415) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:323) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.loadPlugins(CraftServer.java:417) ~[purpur-1.18.2.jar:git-Purpur-1581]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:323) ~[purpur-1.18.2.jar:git-Purpur-1581]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1181) ~[purpur-1.18.2.jar:git-Purpur-1581]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:322) ~[purpur-1.18.2.jar:git-Purpur-1581]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NoSuchMethodError: 'net.kyori.adventure.text.minimessage.MiniMessage$Builder net.kyori.adventure.text.minimessage.MiniMessage$Builder.removeDefaultTransformations()'
        at me.youhavetrouble.purpurextras.PurpurExtras.<init>(PurpurExtras.java:22) ~[PurpurExtras-1.13.jar:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
        at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
        at java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128) ~[?:?]
        at jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:347) ~[?:?]
        at java.lang.Class.newInstance(Class.java:645) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:85) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:153) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        ... 7 more

**Comment by YouHaveTrouble** [comment]
I'm aware. I haven't had a chance to update the plugin yet

**Comment by YouHaveTrouble** [comment]
should be good with [1.13.1](https://github.com/YouHaveTrouble/PurpurExtras/releases/tag/v1.13.1)
